Socint 228 use updated survey event
ONSdigital/sdc-int-cc-service pull request #37
Opened 2021-12-06 17:07 UTC by PeterBochel

See original CR for details on changes: https://collaborate2.ons.gov.uk/jira/browse/SOCINT-228

2021-12-07 13:40 UTC, rpcatling requested changes
a few minor things

2021-12-07 16:14 UTC, spdiaz1000 approved these changes

2021-12-07 16:44 UTC, PeterBochel commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/SurveyUpdateRepositoryIT.java
> +      productRepo.deleteAll();
Test fails if the other deletes are not there.
It fails with a constraint violation exception.

2021-12-07 16:44 UTC, PeterBochel commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/SurveyUpdateRepositoryIT.java
> +        ProductRepository productRepo,
Needed to allow test to run. See below.

2021-12-07 16:44 UTC, PeterBochel commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/SurveyUpdateRepositoryIT.java
> +    // Load a random survey, to make that there is no inteference between the test survey
Typo fixed.

2021-12-07 16:44 UTC, PeterBochel commented on src/main/resources/db/migration/V11__ProductsForSurvey.sql
> +  id UUID NOT NULL,
It is using what has gone before. 
It seems to be only V5 and V9 which use 'id UUID PRIMARY KEY'.
I can see the merits in this but went with the majority

2021-12-07 16:44 UTC, PeterBochel commented on src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, UUID> {}
It's used by the IT test.

2021-12-07 17:08 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/SurveyUpdateRepositoryIT.java
> +      productRepo.deleteAll();
This is not happened when I tried it

2021-12-07 17:09 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/SurveyUpdateRepositoryIT.java
> +        ProductRepository productRepo,
not when I tried it

2021-12-07 17:09 UTC, rpcatling commented on src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, UUID> {}
not when I tried it

2021-12-07 17:10 UTC, rpcatling commented on src/main/resources/db/migration/V11__ProductsForSurvey.sql
> +  id UUID NOT NULL,
OK the majority were pretty much all done my me, but I thought this was the best and most succinct.

2021-12-08 09:13 UTC, PeterBochel commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/SurveyUpdateRepositoryIT.java
> +        ProductRepository productRepo,
Now deleted.

2021-12-08 09:14 UTC, PeterBochel commented on src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/ProductRepository.java
> +public interface ProductRepository extends JpaRepository<Product, UUID> {}
Now deleted.

2021-12-08 09:15 UTC, PeterBochel commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/repository/db/SurveyUpdateRepositoryIT.java
> +      productRepo.deleteAll();
As you say, it works if the 'productRepo' delete is removed.
Now removed :)

2021-12-08 09:50 UTC, rpcatling approved these changes

2021-12-08 09:51 UTC, merged