Socint 435
ONSdigital/sdc-int-cc-service pull request #70
Opened 2022-03-30 12:21 UTC by KieranWardle

https://collaborate2.ons.gov.uk/jira/browse/SOCINT-435

Added check to all user endpoints to only return users who have not been deleted and block deleted users from logging in

2022-04-01 08:07 UTC, rpcatling requested changes
There needs to be some modification to a couple of the Role endpoints to screen out deleted users.  (find users by user-role or admin-role)

2022-04-04 09:14 UTC, philwhiles commented on src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/UserService.java
> +    checkIfDeleted(user);
The same block of code appears numerous times in this class:

    User user =
        userRepository
            .findByIdentity(userIdentity)
            .orElseThrow(() -> new CTPException(Fault.BAD_REQUEST, "User not found"));

    checkIfDeleted(user);

Prime candidate for abstraction.

DRY

2022-04-04 09:16 UTC, philwhiles requested changes
see comment

2022-04-04 11:01 UTC, philwhiles approved these changes

2022-04-04 11:03 UTC, merged